# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   -DLMP_KOKKOS 
PKG_PATH =  
PKG_LIB =   $(KOKKOS_LIBS) 
PKG_CPP_DEPENDS = $(KOKKOS_CPP_DEPENDS) 
PKG_LINK_DEPENDS = $(KOKKOS_LINK_DEPENDS) 

PKG_SYSINC =  $(KOKKOS_CPPFLAGS) $(KOKKOS_CXXFLAGS) 
PKG_SYSLIB =  $(KOKKOS_LDFLAGS) 
PKG_SYSPATH = 
